// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWPWEqsZTLqYqhKKQcSTktwVz2-zUSif8',
    appId: '1:135794821628:web:6c476b83812d44d1454a79',
    messagingSenderId: '135794821628',
    projectId: 'lumora-app-28d86',
    authDomain: 'lumora-app-28d86.firebaseapp.com',
    storageBucket: 'lumora-app-28d86.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFaEIR0fbNeen1kqGuk1OswgwoWraMq9Q',
    appId: '1:135794821628:android:9cad1026bdd05292454a79',
    messagingSenderId: '135794821628',
    projectId: 'lumora-app-28d86',
    storageBucket: 'lumora-app-28d86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO1Xp-QYAv3j4iK05rk528tWRPw4bJLxw',
    appId: '1:135794821628:ios:0713af55aa43aa59454a79',
    messagingSenderId: '135794821628',
    projectId: 'lumora-app-28d86',
    storageBucket: 'lumora-app-28d86.firebasestorage.app',
    iosBundleId: 'com.example.finalSemProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO1Xp-QYAv3j4iK05rk528tWRPw4bJLxw',
    appId: '1:135794821628:ios:0713af55aa43aa59454a79',
    messagingSenderId: '135794821628',
    projectId: 'lumora-app-28d86',
    storageBucket: 'lumora-app-28d86.firebasestorage.app',
    iosBundleId: 'com.example.finalSemProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWPWEqsZTLqYqhKKQcSTktwVz2-zUSif8',
    appId: '1:135794821628:web:4b128e155b3a0f63454a79',
    messagingSenderId: '135794821628',
    projectId: 'lumora-app-28d86',
    authDomain: 'lumora-app-28d86.firebaseapp.com',
    storageBucket: 'lumora-app-28d86.firebasestorage.app',
  );

}
