// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpM4ktrclwb4lAF9fPwr7S_ak_3ti8xjQ',
    appId: '1:842088082758:web:c5537386bb9c2ba6d38947',
    messagingSenderId: '842088082758',
    projectId: 'finalproject-9b49e',
    authDomain: 'finalproject-9b49e.firebaseapp.com',
    storageBucket: 'finalproject-9b49e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvPPdjQhKvRjN-DokesZiv-0zVd41jXxI',
    appId: '1:842088082758:android:ee39270149008df4d38947',
    messagingSenderId: '842088082758',
    projectId: 'finalproject-9b49e',
    storageBucket: 'finalproject-9b49e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWOW9ujLXp2EDuKlkDy3nAl0pmk2Wx9NM',
    appId: '1:842088082758:ios:e98ef45fab3fff4bd38947',
    messagingSenderId: '842088082758',
    projectId: 'finalproject-9b49e',
    storageBucket: 'finalproject-9b49e.firebasestorage.app',
    iosBundleId: 'com.example.finalMadForebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWOW9ujLXp2EDuKlkDy3nAl0pmk2Wx9NM',
    appId: '1:842088082758:ios:e98ef45fab3fff4bd38947',
    messagingSenderId: '842088082758',
    projectId: 'finalproject-9b49e',
    storageBucket: 'finalproject-9b49e.firebasestorage.app',
    iosBundleId: 'com.example.finalMadForebase',
  );
}